apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: apache-php
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    dns: true
    ports:
    - protocol: "HTTPS"
      targetPort: 1337
  healthcheck:
    enabled: true
  podTemplate:
    template:
      spec:
        containers:
        - name: challenge
          volumeMounts:
          - name: sessions
            mountPath: /mnt/disks/sessions
          - name: uploads
            mountPath: /mnt/disks/uploads
        volumes:
        - name: sessions
          persistentVolumeClaim:
            claimName: apache-php-sessions
        - name: uploads
          persistentVolumeClaim:
            claimName: apache-php-uploads
  persistentVolumeClaims:
    - apache-php-sessions
    - apache-php-uploads
  horizontalPodAutoscalerSpec:
    minReplicas: 2
    maxReplicas: 2
    targetCPUUtilizationPercentage: 50 
