apiVersion: v1
kind: Namespace
metadata:
  name: mychal

---

apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: mychal
  namespace: mychal
spec:
  # Add fields here
  image: "quay.io/aliciafmachado/bash:latest"
  deployed: true
  network:
    public: true
    dns: true
    domainName: example.com
    ports:
    - protocol: "TCP"
      port: 3
      targetPort: 1337
    - protocol: "HTTPS"
      targetPort: 1338
