apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: mychal
spec:
  # Add fields here
  imageTemplate: "memcached:1.4.36-alpine"
  deployed: true
  network:
    public: true
    dns: true
    ports:
    - protocol: "HTTPS"
      targetPort: 1338

