apiVersion: v1
kind: Namespace
metadata:
  name: mychal

---

apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: mychal
  namespace: mychal
spec:
  # Add fields here
  imageTemplate: "quay.io/aliciafmachado/bash:latest"
  deployed: true
  network:
    public: true
    dns: true
    ports:
    - protocol: "TCP"
      port: 3
      targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
        - name: extra
          image: "memcached:1.4.36-alpine"
  horizontalPodAutoscalerSpec:
    maxReplicas: 2
    minReplicas: 2
    targetCPUUtilizationPercentage: 50

