# permissions for end users to view challenges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: challenge-viewer-role
rules:
- apiGroups:
  - operator.kctf.dev
  resources:
  - challenges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kctf.dev
  resources:
  - challenges/status
  verbs:
  - get
