apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: bash
spec:
  # Add fields here
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    dns: true
  healthcheck:
    enabled: true
