apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: apache-others
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    dns: true
    ports:
    - protocol: "HTTPS"
      targetPort: 1337
  healthcheck:
    enabled: true
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: apache-run
                mountPath: /var/run/apache2
              - name: apache-log
                mountPath: /var/log/apache2
            securityContext:
              runAsUser: 0
        volumes:
          - name: apache-log
            emptyDir: {}
          - name: apache-run
            emptyDir: {}
