apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: xss-bot
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    dns: true
  healthcheck:
    enabled: true
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: slash-tmp
                mountPath: /tmp
        volumes:
          - name: slash-tmp
            emptyDir: {}
